#--*--coding:utf-8 --*--
#MAIL_SERVER="localhost"
MAIL_SERVER="smtp.163.com"
MAIL_PORT=25
#MAIL_USE_TLS=False
#MAIL_USE_SSL=False
#MAIL_DEBUG=app.debug
#MAIL_USERNAME=None
MAIL_USERNAME="15851390734@163.com"
MAIL_PASSWORD="hsz881224"
#MAIL_PASSWORD=None
#MAIL_DEFAULT_SENDER=None
MAIL_DEFAULT_SENDER="15851390734@163.com"
#MAIL_MAX_EMAILS=None
#MAIL_SUPPRESS_SEND=app.testing
#MAIL_ASCII_ATTACHMENTS=False