# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='squarerpc_service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x11squarerpc_service\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\x01\x32Z\n\rSquareService\x12I\n\x0brangeSquare\x12\x1a.squarerpc_service.Message\x1a\x1a.squarerpc_service.Message\"\x00\x30\x01\x62\x06proto3')
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='squarerpc_service.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='squarerpc_service.Message.message', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:squarerpc_service.Message)
  ))
_sym_db.RegisterMessage(Message)



_SQUARESERVICE = _descriptor.ServiceDescriptor(
  name='SquareService',
  full_name='squarerpc_service.SquareService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=61,
  serialized_end=151,
  methods=[
  _descriptor.MethodDescriptor(
    name='rangeSquare',
    full_name='squarerpc_service.SquareService.rangeSquare',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SQUARESERVICE)

DESCRIPTOR.services_by_name['SquareService'] = _SQUARESERVICE

# @@protoc_insertion_point(module_scope)
